# Generated by Django 5.2.2 on 2025-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
